### ISSUE TITLE
Panic if the vendored libs are not updated prior to making the bin

### ISSUE THREAD

**Issue by CharlyF** [JulienBalestra/kube-csr#47]
**Describe what happened:**

cloned the repo, run `sudo make`, get a panic when trying to use the binary

```
charly@chk:~/go/src/github.com/CharlyF/kube-csr$ ./kube-csr -h 
./kube-csr flag redefined: log_dir
panic: ./kube-csr flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc4200ca000, 0x126ed40, 0xc4200c8180, 0x117ad4b, 0x7, 0x11a5e96, 0x2f)
	/usr/local/go/src/flag/flag.go:810 +0x540
flag.(*FlagSet).StringVar(0xc4200ca000, 0xc4200c8180, 0x117ad4b, 0x7, 0x0, 0x0, 0x11a5e96, 0x2f)
	/usr/local/go/src/flag/flag.go:713 +0x8b
flag.(*FlagSet).String(0xc4200ca000, 0x117ad4b, 0x7, 0x0, 0x0, 0x11a5e96, 0x2f, 0xc4200c8170)
	/usr/local/go/src/flag/flag.go:726 +0x8b
flag.String(0x117ad4b, 0x7, 0x0, 0x0, 0x11a5e96, 0x2f, 0xc4200c8150)
	/usr/local/go/src/flag/flag.go:733 +0x69
```

running `dep ensure -v` and `sudo make re` fixes the issue. 

**Describe what you expected:**

Making the bin works right away, have a clearer error message.
This is the issue that helped me solve this:
https://github.com/kubernetes/kubernetes/issues/25572

**Comment by CharlyF** [comment]
As I forked it it's in `${GOPATH}/src/github.com/CharlyF/kube-csr`.
I don't think sudo is required, but I've had some issues with my dev machine trying to `make` in the past. 
I think it was a problem with the path indeed!
